<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Animal;
use App\Models\Sale;
use App\Models\Expense;
use App\Models\WaterSale;
use App\Models\InventoryItem;
use App\Models\Worker;
use Carbon\Carbon;

class DummyDataSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Livestock
        $livestockData = [
            ['type' => 'cattle', 'tag_id' => 'C-001', 'breed' => 'Sokoto Gudali', 'quantity' => 120, 'current_value' => 350000, 'purchase_price' => 300000],
            ['type' => 'poultry', 'tag_id' => 'P-001', 'breed' => 'Broiler', 'quantity' => 5000, 'current_value' => 4500, 'purchase_price' => 1500],
            ['type' => 'goat', 'tag_id' => 'G-001', 'breed' => 'Red Sokoto', 'quantity' => 200, 'current_value' => 45000, 'purchase_price' => 25000],
            ['type' => 'sheep', 'tag_id' => 'S-001', 'breed' => 'Balami', 'quantity' => 150, 'current_value' => 60000, 'purchase_price' => 40000],
        ];

        foreach ($livestockData as $data) {
            Animal::create(array_merge($data, [
                'age_months' => rand(6, 36),
                'status' => 'active',
                'notes' => 'Generated by seeder'
            ]));
        }

        // 2. Workers
        $roles = ['Farm Manager', 'Herdsman', 'Veterinarian', 'Security', 'Driver'];
        foreach ($roles as $role) {
            Worker::create([
                'name' => 'Worker ' . $role,
                'role' => $role,
                'phone' => '080' . rand(10000000, 99999999),
                'salary' => rand(30000, 150000),
                'hire_date' => Carbon::now()->subMonths(rand(1, 24)),
                'status' => 'active'
            ]);
        }

        // 3. Inventory Items
        $inventoryData = [
            ['name' => 'Poultry Feed', 'category' => 'Feed', 'quantity' => 150, 'unit' => 'Bags', 'unit_cost' => 12000, 'min_stock_level' => 20],
            ['name' => 'Cattle Feed', 'category' => 'Feed', 'quantity' => 50, 'unit' => 'Bags', 'unit_cost' => 15000, 'min_stock_level' => 10],
            ['name' => 'Antibiotics', 'category' => 'Medicine', 'quantity' => 30, 'unit' => 'Bottles', 'unit_cost' => 5000, 'min_stock_level' => 5],
            ['name' => 'Vaccine (NDV)', 'category' => 'Medicine', 'quantity' => 5, 'unit' => 'Vials', 'unit_cost' => 15000, 'min_stock_level' => 10],
        ];

        foreach ($inventoryData as $data) {
            InventoryItem::create($data);
        }

        // 4. Sales & Expenses over the last 12 months
        $saleCategories = ['Livestock', 'Dairy', 'Eggs', 'Crops'];
        $expenseCategories = ['Feed', 'Medicine', 'Salaries', 'Maintenance', 'Utilities'];
        
        $now = Carbon::now();
        
        for ($i = 0; $i < 12; $i++) {
            $monthDate = $now->copy()->subMonths($i);
            
            // Create 3-8 sales per month
            $numSales = rand(3, 8);
            for ($s = 0; $s < $numSales; $s++) {
                $qty = rand(10, 100);
                $unitPrice = rand(1000, 50000);
                Sale::create([
                    'date' => $monthDate->copy()->subDays(rand(1, 28)),
                    'category' => $saleCategories[array_rand($saleCategories)],
                    'item' => 'Sale Item ' . rand(1, 100),
                    'quantity' => $qty,
                    'unit' => 'Units',
                    'unit_price' => $unitPrice,
                    'total_amount' => $qty * $unitPrice,
                    'buyer' => 'Customer ' . rand(1, 50)
                ]);
            }
            
            // Create 3-8 expenses per month
            $numExpenses = rand(3, 8);
            for ($e = 0; $e < $numExpenses; $e++) {
                Expense::create([
                    'date' => $monthDate->copy()->subDays(rand(1, 28)),
                    'category' => $expenseCategories[array_rand($expenseCategories)],
                    'description' => 'Expense Item ' . rand(1, 100),
                    'amount' => rand(10000, 200000),
                    'vendor' => 'Vendor ' . rand(1, 20)
                ]);
            }
            
            // Create Water Sales
            $numWaterSales = rand(2, 5);
            for ($w = 0; $w < $numWaterSales; $w++) {
                $qty = rand(100, 500);
                $unitPrice = 150;
                WaterSale::create([
                    'date' => $monthDate->copy()->subDays(rand(1, 28)),
                    'quantity' => $qty,
                    'unit_price' => $unitPrice,
                    'total_amount' => $qty * $unitPrice,
                    'buyer' => 'Water Customer ' . rand(1, 30),
                    'distribution_area' => 'Zone ' . rand(1, 5)
                ]);
            }
        }
    }
}
